# Site settings
title: Rohan Kalvade Deshpande
description: Rohan Kalvade's personal webpage.
author: Rohan Kalvade Deshpande
url: https://rohand.me/

markdown: kramdown
baseurl:

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
