# Site settings
title: Rohan Kalvade Deshpande
description: Rohan Kalvade's personal webpage.
author: Rohan Kalvade Deshpande
url: https://rohanvdeshpande.github.io/
quote: 'To invent, you need a good imagination and a pile of junk. -Thomas A. Edison'
footertext: 'This website was created by <strong>Rohan Kalvade</strong> from scratch. The website was made with over <strong>1,500 lines</strong> of HTML code and <strong>18,900</strong> of CSS code!'

markdown: kramdown
baseurl:

sass:
  sass_dir: assets/css
  style: :compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
